# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title 
#'
#' @description
#' 
#'
#' @param X 
#' @param k 
#' @param tore 
#' @param toreBound 
#'
#' @details
#'
#'
#'
#' @return 
#'
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#'
#' @seealso
#' 
#' @export
calibRaking <- function(Xs, d, total, q, max_iter = 500L, tol = 1e-9) {
    .Call(`_transportMatching_calibRaking`, Xs, d, total, q, max_iter, tol)
}

